wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1661593935
    t:
      1:
      - 1
      - 55
      3:
      - 13
      4: 3.8.3
      5: 0.12.18
      8:
      - 3
      - 5
